export const ADD_NORTH_CARD = 'HANDS_ADD_NORTH_CARD';
export const REMOVE_NORTH_CARD = 'HANDS_REMOVE_NORTH_CARD';
export const ADD_WEST_CARD = 'HANDS_ADD_WEST_CARD';
export const REMOVE_WEST_CARD = 'HANDS_REMOVE_WEST_CARD';
export const ADD_EAST_CARD = 'HANDS_ADD_EAST_CARD';
export const REMOVE_EAST_CARD = 'HANDS_REMOVE_EAST_CARD';
export const ADD_SOUTH_CARD = 'HANDS_ADD_SOUTH_CARD';
export const REMOVE_SOUTH_CARD = 'HANDS_REMOVE_SOUTH_CARD';
