export const ADD_NORTH_CARD = 'BOARDS_ADD_NORTH_CARD';
export const REMOVE_NORTH_CARD = 'BOARDS_REMOVE_NORTH_CARD';
export const ADD_WEST_CARD = 'BOARDS_ADD_WEST_CARD';
export const REMOVE_WEST_CARD = 'BOARDS_REMOVE_WEST_CARD';
export const ADD_EAST_CARD = 'BOARDS_ADD_EAST_CARD';
export const REMOVE_EAST_CARD = 'BOARDS_REMOVE_EAST_CARD';
export const ADD_SOUTH_CARD = 'BOARDS_ADD_SOUTH_CARD';
export const REMOVE_SOUTH_CARD = 'BOARDS_REMOVE_SOUTH_CARD';
